///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexTestMvcSuite.TestCases
{
    /// <summary>
    ///The Http_Browser_ClearCache recording.
    /// </summary>
    [TestModule("818b75ec-b935-4da4-9a48-16dc56c3fd27", ModuleType.Recording, 1)]
    public partial class Http_Browser_ClearCache : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexTestMvcSuite.RanorexTestMvcSuiteRepository repository.
        /// </summary>
        public static RanorexTestMvcSuite.RanorexTestMvcSuiteRepository repo = RanorexTestMvcSuite.RanorexTestMvcSuiteRepository.Instance;

        static Http_Browser_ClearCache instance = new Http_Browser_ClearCache();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Http_Browser_ClearCache()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Http_Browser_ClearCache Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Http_Browser_ClearCache_Open_Browser();
            Delay.Milliseconds(0);
            
            Mouse_Click_НачальнаяСтраницаMozillaFirefoxMoz();
            Delay.Milliseconds(0);
            
            Mouse_Click_Настройки();
            Delay.Milliseconds(0);
            
            Mouse_Click_Приватность();
            Delay.Milliseconds(0);
            
            Mouse_Click_УдалитьВашуНедавнююИсторию();
            Delay.Milliseconds(0);
            
            Mouse_Click_УдалитьСейчас();
            Delay.Milliseconds(0);
            
            Mouse_Click_ButtonOK();
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
}
