///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace RanorexTestMvcSuite.TestCases
{
    public partial class Http_Browser_ClearCache
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_ButtonOK()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Настройки.ButtonOK' at 36;10.", repo.Настройки.ButtonOKInfo);
            repo.Настройки.ButtonOK.Click("36;10");
        }

        public void Mouse_Click_УдалитьСейчас()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'УдалениеВсейИстории.УдалитьСейчас' at 36;11.", repo.УдалениеВсейИстории.УдалитьСейчасInfo);
            repo.УдалениеВсейИстории.УдалитьСейчас.Click("36;11");
        }

        public void Mouse_Click_УдалитьВашуНедавнююИсторию()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Настройки.УдалитьВашуНедавнююИсторию' at 73;4.", repo.Настройки.УдалитьВашуНедавнююИсториюInfo);
            repo.Настройки.УдалитьВашуНедавнююИсторию.Click("73;4");
        }

        public void Mouse_Click_Настройки()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Firefox.Настройки' at 51;9.", repo.Firefox.НастройкиInfo);
            repo.Firefox.Настройки.Click("51;9");
        }

        public void Mouse_Click_НачальнаяСтраницаMozillaFirefoxMoz()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'НачальнаяСтраницаMozillaFirefoxMoz.НачальнаяСтраницаMozillaFirefoxMoz' at 271;10.", repo.НачальнаяСтраницаMozillaFirefoxMoz.НачальнаяСтраницаMozillaFirefoxMozInfo);
            repo.НачальнаяСтраницаMozillaFirefoxMoz.НачальнаяСтраницаMozillaFirefoxMoz.Click("271;10");
        }

        public void Http_Browser_ClearCache_Open_Browser()
        {
            Report.Log(ReportLevel.Info, "Website", "Opening web site '' with browser 'firefox' in normal mode.");
            Host.Local.OpenBrowser("", "firefox", "", false, false);
            //BrowserHelper.Open_Browser();

        }
        
        public void Http_Browser_ClearCache_Close_Browser()
        {
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'LoginMozillaFirefox'.", repo.LoginMozillaFirefox.SelfInfo);
            Host.Local.CloseApplication(repo.НачальнаяСтраницаMozillaFirefoxMoz.НачальнаяСтраницаMozillaFirefoxMoz, new Duration(0));
        }

        public void Mouse_Click_Приватность()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Настройки.Приватность' at 43;21.", repo.Настройки.ПриватностьInfo);
            repo.Настройки.Приватность.Click("43;21");
        }     
       
    }
}