///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace RanorexTestMvcSuite.TestCases
{
    public partial class TC_EditCurrentUserProfileAtPositive
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_Выход()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Выход' at 26;9.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ВыходInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Выход.Click("26;9");
        }

        public void Validate_Email22()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleValue='fls7@fls.com') on item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Email2'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email2Info);
            Validate.Attribute(repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email2Info, "AccessibleValue", "fls7@fls.com");
        }

        public void Validate_Email2()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='fls7@fls.com') on item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Email2'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email2Info);
            Validate.Attribute(repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email2Info, "Text", "fls7@fls.com");
        }

        public void Validate_Фамилия2()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleValue='TestLastName') on item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo);
            Validate.Attribute(repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo, "AccessibleValue", "TestLastName");
        }

        public void Validate_Фамилия()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TestLastName') on item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo);
            Validate.Attribute(repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo, "Text", "TestLastName");
        }

        public void Validate_TextИмя2()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleValue='TestFirstName') on item 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo);
            Validate.Attribute(repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo, "AccessibleValue", "TestFirstName");
        }

        public void Validate_TextИмя()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TestFirstName') on item 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo);
            Validate.Attribute(repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo, "Text", "TestFirstName");
        }

        public void Mouse_Click_Fls72()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IndexMozillaFirefox.Index.Fls7' at 7;7.", repo.IndexMozillaFirefox.Index.Fls7Info);
            repo.IndexMozillaFirefox.Index.Fls7.Click("7;7");
        }

        public void Mouse_Click_Сохранить()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Сохранить' at 51;16.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.СохранитьInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Сохранить.Click("51;16");
        }

        public void Key_Sequence_MozillaFirefox2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}@{LShiftKey up}fls.com' with focus on 'MozillaFirefox'.", repo.MozillaFirefox.SelfInfo);
            repo.MozillaFirefox.Self.PressKeys("{LShiftKey down}@{LShiftKey up}fls.com");
        }

        public void Key_Sequence_MozillaFirefox()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'MozillaFirefox'.", repo.MozillaFirefox.SelfInfo);
            repo.MozillaFirefox.Self.PressKeys("fls7");
        }

        public void Mouse_Up_Email1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Email1' at 27;2.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email1Info);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email1.MoveTo("27;2");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_MozillaFirefox()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MozillaFirefox' at 449;310.", repo.MozillaFirefox.SelfInfo);
            repo.MozillaFirefox.Self.MoveTo("449;310");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Key_Sequence_Фамилия2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}T{LShiftKey up}est{LShiftKey down}L{LShiftKey up}ast{LShiftKey down}N{LShiftKey up}ame' with focus on 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия.PressKeys("{LShiftKey down}T{LShiftKey up}est{LShiftKey down}L{LShiftKey up}ast{LShiftKey down}N{LShiftKey up}ame");
        }

        public void Key_Sequence_Фамилия()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия.PressKeys("{Delete}");
        }

        public void Mouse_Up_Фамилия1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия1' at 98;11.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия1Info);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия1.MoveTo("98;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_Фамилия()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия' at 214;14.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия.MoveTo("214;14");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Key_Sequence_TextИмя2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}T{LShiftKey up}est{LShiftKey down}F{LShiftKey up}irst{LShiftKey down}N{LShiftKey up}ame' with focus on 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя.PressKeys("{LShiftKey down}T{LShiftKey up}est{LShiftKey down}F{LShiftKey up}irst{LShiftKey down}N{LShiftKey up}ame");
        }

        public void Key_Sequence_TextИмя()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя.PressKeys("{Delete}");
        }

        public void Mouse_Up_TextИмя1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя1' at 29;14.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя1Info);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя1.MoveTo("29;14");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_TextИмя()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя' at 247;19.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя.MoveTo("247;19");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_Fls7()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IndexMozillaFirefox.Index.Fls7' at 8;9.", repo.IndexMozillaFirefox.Index.Fls7Info);
            repo.IndexMozillaFirefox.Index.Fls7.Click("8;9");
        }

        public void Mouse_Click_Войти()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Войти' at 33;12.", repo.LoginMozillaFirefox.Login.ВойтиInfo);
            repo.LoginMozillaFirefox.Login.Войти.Click("33;12");
        }

        public void Key_Sequence_Пароль3()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'LoginMozillaFirefox.Login.Пароль'.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.PressKeys("fls7");
        }

        public void Key_Sequence_Пароль2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}ls7' with focus on 'LoginMozillaFirefox.Login.Пароль'.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.PressKeys("{Back}ls7");
        }

        public void Key_Sequence_Пароль()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'f;' with focus on 'LoginMozillaFirefox.Login.Пароль'.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.PressKeys("f;");
        }

        public void Mouse_Click_Пароль()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Пароль' at 223;21.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.Click("223;21");
        }

        public void Key_Sequence_Логин()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'LoginMozillaFirefox.Login.Логин'.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.PressKeys("fls7");
        }

        public void Mouse_Click_Логин()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Логин' at 98;17.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.Click("98;17");
        }

        //public void TC_EditCurrentUserProfileAtPositive_Open_Browser()
        //{
        //    BrowserHelper.Open_Browser();
        //}
        
        public void Close_Application()
        {
        	BrowserHelper.Close_Application_LoginMozillaFirefox();
        }

        public void Key_Sequence_Логин2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'LoginMozillaFirefox.Login.Логин'.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.PressKeys("{Tab}");
        }

    }
}