///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace RanorexTestMvcSuite.TestCases
{
    public partial class TC_EditCurrentUserProfileAtNegative
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_Выход()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IndexMozillaFirefox.Выход' at 27;12.", repo.IndexMozillaFirefox.ВыходInfo);
            repo.IndexMozillaFirefox.Выход.Click("27;12");
        }

        public void Mouse_Click_Назад()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Назад' at 29;8.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.НазадInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Назад.Click("29;8");
        }

        public void Validate_ВведитеEmail()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Введите email') on item 'MozillaFirefox.HttpLocalhost6333AccountRegister.ВведитеEmail'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ВведитеEmailInfo);
            Validate.Attribute(repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ВведитеEmailInfo, "AccessibleName", "Введите email");
        }

        public void Mouse_Click_Сохранить3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Сохранить' at 43;13.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.СохранитьInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Сохранить.Click("43;13");
        }

        public void Key_Sequence_Email2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'MozillaFirefox.HttpLocalhost6333AccountRegister.Email2'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email2Info);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email2.PressKeys("{Delete}");
        }

        public void Mouse_Up_Email3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Email3' at 80;16.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email3Info);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email3.MoveTo("80;16");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_Email2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Email2' at 191;24.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email2Info);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Email2.MoveTo("191;24");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Validate_TheФамилияFieldIsRequired()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='The Фамилия field is required.') on item 'MozillaFirefox.HttpLocalhost6333AccountRegister.TheФамилияFieldIsRequired'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TheФамилияFieldIsRequiredInfo);
            Validate.Attribute(repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TheФамилияFieldIsRequiredInfo, "AccessibleName", "The Фамилия field is required.");
        }

        public void Mouse_Click_Сохранить2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Сохранить' at 37;17.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.СохранитьInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Сохранить.Click("37;17");
        }

        public void Key_Sequence_Фамилия()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия.PressKeys("{Delete}");
        }

        public void Mouse_Up_Фамилия2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия2' at 8;5.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия2Info);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия2.MoveTo("8;5");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_Фамилия()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия' at 149;18.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.ФамилияInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Фамилия.MoveTo("149;18");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_Fls72()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IndexMozillaFirefox.Index.Fls7' at 1;9.", repo.IndexMozillaFirefox.Index.Fls7Info);
            repo.IndexMozillaFirefox.Index.Fls7.Click("1;9");
        }

        public void Mouse_Click_Сохранить()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MozillaFirefox.HttpLocalhost6333AccountRegister.Сохранить' at 49;17.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.СохранитьInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.Сохранить.Click("49;17");
        }

        public void Key_Sequence_TextИмя()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя'.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя.PressKeys("{Delete}");
        }

        public void Mouse_Up_TextИмя1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя1' at 183;19.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя1Info);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя1.MoveTo("183;19");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_TextИмя()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя' at 179;16.", repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмяInfo);
            repo.MozillaFirefox.HttpLocalhost6333AccountRegister.TextИмя.MoveTo("179;16");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Click_Fls7()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IndexMozillaFirefox.Index.Fls7' at 9;10.", repo.IndexMozillaFirefox.Index.Fls7Info);
            repo.IndexMozillaFirefox.Index.Fls7.Click("9;10");
        }

        public void Mouse_Click_Войти()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Войти' at 17;13.", repo.LoginMozillaFirefox.Login.ВойтиInfo);
            repo.LoginMozillaFirefox.Login.Войти.Click("17;13");
        }

        public void Key_Sequence_Пароль()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7fls7' with focus on 'LoginMozillaFirefox.Login.Пароль'.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.PressKeys("fls7fls7");
        }

        public void Mouse_Click_Пароль()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Пароль' at 227;24.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.Click("227;24");
        }

        public void Key_Sequence_Логин()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'LoginMozillaFirefox.Login.Логин'.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.PressKeys("fls7");
        }

        public void Mouse_Click_Логин()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Логин' at 207;20.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.Click("207;20");
        }

        //public void EditCurrentUserProfileAtNegative_Open_Browser()
        //{
        //    BrowserHelper.Open_Browser();
        //}
        
        public void Close_App()
        {
        	BrowserHelper.Close_Application_LoginMozillaFirefox();
        }

        public void Key_Sequence_Логин2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'LoginMozillaFirefox.Login.Логин'.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.PressKeys("{Tab}");
        }

    }
}