///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace RanorexTestMvcSuite.TestCases
{
    public partial class TC_LoginAtNegative
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void Close_Application_LoginMozillaFirefox()
        {
            BrowserHelper.Close_Application_LoginMozillaFirefox();
        }

        public void Validate_ВведитеЛогин2()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginMozillaFirefox.Login.ВведитеЛогин'.", repo.LoginMozillaFirefox.Login.ВведитеЛогинInfo);
            Validate.Exists(repo.LoginMozillaFirefox.Login.ВведитеЛогинInfo);
        }

        public void Mouse_Click_Войти2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Войти' at 13;15.", repo.LoginMozillaFirefox.Login.ВойтиInfo);
            repo.LoginMozillaFirefox.Login.Войти.Click("13;15");
        }

        public void Key_Sequence_Пароль()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7fls7' with focus on 'LoginMozillaFirefox.Login.Пароль'.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.PressKeys("fls7fls7");
        }

        public void Mouse_Click_Пароль(string argument1)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Пароль' at 155;18.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.Click("155;18");
        }

        public void Validate_ВведитеЛогин()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginMozillaFirefox.Login.ВведитеЛогин'.", repo.LoginMozillaFirefox.Login.ВведитеЛогинInfo);
            Validate.Exists(repo.LoginMozillaFirefox.Login.ВведитеЛогинInfo);
        }

        public void Key_Sequence_Логин2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'LoginMozillaFirefox.Login.Логин'.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.PressKeys("{Delete}");
        }

        public void Mouse_Up_Логин1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'LoginMozillaFirefox.Login.Логин1' at 142;7.", repo.LoginMozillaFirefox.Login.Логин1Info);
            repo.LoginMozillaFirefox.Login.Логин1.MoveTo("142;7");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
        }

        public void Mouse_Down_Логин()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LoginMozillaFirefox.Login.Логин' at 219;11.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.MoveTo("219;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
        }

        public void Validate_ВведитеПароль1()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginMozillaFirefox.Login.ВведитеПароль1'.", repo.LoginMozillaFirefox.Login.ВведитеПароль1Info);
            Validate.Exists(repo.LoginMozillaFirefox.Login.ВведитеПароль1Info);
        }

        public void Mouse_Click_Войти()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Войти' at 20;13.", repo.LoginMozillaFirefox.Login.ВойтиInfo);
            repo.LoginMozillaFirefox.Login.Войти.Click("20;13");
        }

        public void Key_Sequence_Логин()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'LoginMozillaFirefox.Login.Логин'.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.PressKeys("fls7");
        }

        public void Mouse_Click_Логин()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Логин' at 221;17.", repo.LoginMozillaFirefox.Login.ЛогинInfo);
            repo.LoginMozillaFirefox.Login.Логин.Click("221;17");
        }

        //public void TC_LoginAtNegative_Open_Browser()
        //{
        //    BrowserHelper.Open_Browser();
        //}

        public void MergedUserCodeMethod()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LoginMozillaFirefox.Login.Пароль' at 146;15.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.MoveTo("146;15");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'LoginMozillaFirefox.Login.Пароль1' at 58;7.", repo.LoginMozillaFirefox.Login.Пароль1Info);
            repo.LoginMozillaFirefox.Login.Пароль1.MoveTo("58;7");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'LoginMozillaFirefox.Login.Пароль'.", repo.LoginMozillaFirefox.Login.ПарольInfo);
            repo.LoginMozillaFirefox.Login.Пароль.PressKeys("{Delete}");
        }
    }
}