///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexTestMvcSuite.TestCases
{
    /// <summary>
    ///The TC_RegistrationAtPositive recording.
    /// </summary>
    [TestModule("3c88268f-64f7-4965-bb0f-c425fffe938d", ModuleType.Recording, 1)]
    public partial class TC_RegistrationAtPositive : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexTestMvcSuite.RanorexTestMvcSuiteRepository repository.
        /// </summary>
        public static RanorexTestMvcSuite.RanorexTestMvcSuiteRepository repo = RanorexTestMvcSuite.RanorexTestMvcSuiteRepository.Instance;

        static TC_RegistrationAtPositive instance = new TC_RegistrationAtPositive();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TC_RegistrationAtPositive()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TC_RegistrationAtPositive Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Mouse_Click_Зарегистрироваться();
            Delay.Milliseconds(0);
            
            Mouse_Click_Логин();
            Delay.Milliseconds(0);
            
            Key_Sequence_Login();
            Delay.Milliseconds(0);
            
            Mouse_Click_Email();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email2();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email3();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email4();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email5();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email6();
            Delay.Milliseconds(0);
            
            Mouse_Click_Пароль();
            Delay.Milliseconds(0);
            
            Key_Sequence_Пароль();
            Delay.Milliseconds(0);
            
            Key_Sequence_Пароль2();
            Delay.Milliseconds(0);
            
            Key_Sequence_Пароль3();
            Delay.Milliseconds(0);
            
            Mouse_Click_ПодтверждениеПароля();
            Delay.Milliseconds(0);
            
            Key_Sequence_ПодтверждениеПароля();
            Delay.Milliseconds(0);
            
            Key_Sequence_ПодтверждениеПароля2();
            Delay.Milliseconds(0);
            
            Mouse_Click_Зарегистрироваться2();
            Delay.Milliseconds(100);
            
            Validate_Find();
            Delay.Milliseconds(0);
            
            Mouse_Click_Выход();
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
}
