///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexTestMvcSuite.TestCases
{
    /// <summary>
    ///The TC_RegistrationAtNegative recording.
    /// </summary>
    [TestModule("d042a881-a7c1-42d4-b953-68b13dc31c20", ModuleType.Recording, 1)]
    public partial class TC_RegistrationAtNegative : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexTestMvcSuite.RanorexTestMvcSuiteRepository repository.
        /// </summary>
        public static RanorexTestMvcSuite.RanorexTestMvcSuiteRepository repo = RanorexTestMvcSuite.RanorexTestMvcSuiteRepository.Instance;

        static TC_RegistrationAtNegative instance = new TC_RegistrationAtNegative();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TC_RegistrationAtNegative()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TC_RegistrationAtNegative Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Mouse_Click_Зарегистрироваться2();
            Delay.Milliseconds(0);
            
            Validate_ВведитеЛогин();
            Delay.Milliseconds(0);
            
            Validate_ВведитеEmail();
            Delay.Milliseconds(0);
            
            Validate_ВведитеПароль();
            Delay.Milliseconds(0);
            
            Mouse_Click_Логин();
            Delay.Milliseconds(0);
            
            Key_Sequence_Логин();
            Delay.Milliseconds(0);
            
            Key_Sequence_Логин2();
            Delay.Milliseconds(0);
            
            Key_Sequence_Логин3();
            Delay.Milliseconds(0);
            
            Mouse_Click_Зарегистрироваться3();
            Delay.Milliseconds(0);
            
            Validate_ВведитеEmail2();
            Delay.Milliseconds(0);
            
            Validate_ВведитеПароль2();
            Delay.Milliseconds(0);
            
            Mouse_Click_Email();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email2();
            Delay.Milliseconds(0);
            
            Mouse_Click_Зарегистрироваться4();
            Delay.Milliseconds(0);
            
            Validate_ВведитеПароль3();
            Delay.Milliseconds(0);
            
            Mouse_Click_Пароль();
            Delay.Milliseconds(0);
            
            Key_Sequence_Пароль();
            Delay.Milliseconds(0);
            
            Key_Sequence_Пароль2();
            Delay.Milliseconds(0);
            
            Key_Sequence_Пароль3();
            Delay.Milliseconds(0);
            
            Mouse_Click_Зарегистрироваться5();
            Delay.Milliseconds(0);
            
            Validate_ПаролиНеСовпадают();
            Delay.Milliseconds(0);
            
            Mouse_Down_Email();
            Delay.Milliseconds(0);
            
            Mouse_Up_None();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email3();
            Delay.Milliseconds(0);
            
            Mouse_Click_Зарегистрироваться6();
            Delay.Milliseconds(0);
            
            Validate_ВведитеEmail3();
            Delay.Milliseconds(0);
            
            Mouse_Click_Email2();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email4();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email5();
            Delay.Milliseconds(0);
            
            Key_Sequence_Email6();
            Delay.Milliseconds(0);
            
            Mouse_Click_Логин2();
            Delay.Milliseconds(0);
            
            Mouse_Down_Логин();
            Delay.Milliseconds(0);
            
            Mouse_Up_Логин1();
            Delay.Milliseconds(0);
            
            Key_Sequence_Логин4();
            Delay.Milliseconds(0);
            
            Validate_ВведитеЛогин2();
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
}
