///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace RanorexTestMvcSuite.TestCases
{
    public partial class TC_SelectLanguagesOnAllPages
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_Выход()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Grouping.Выход' at 24;11.", repo.LoginMozillaFirefox.Grouping.ВыходInfo);
            repo.LoginMozillaFirefox.Grouping.Выход.Click("24;11");
        }

        public void Mouse_Click_Separator4()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Separator' at 81;15.", repo.LoginMozillaFirefox.SeparatorInfo);
            repo.LoginMozillaFirefox.Separator.Click("81;15");
        }

        public void Validate_Save()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Save') on item 'LoginMozillaFirefox.Grouping.Save'.", repo.LoginMozillaFirefox.Grouping.SaveInfo);
            Validate.Attribute(repo.LoginMozillaFirefox.Grouping.SaveInfo, "Text", "Save");
        }

        public void Mouse_Click_Separator3()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Separator' at 112;11.", repo.LoginMozillaFirefox.SeparatorInfo);
            repo.LoginMozillaFirefox.Separator.Click("112;11");
        }

        public void Validate_Сохранить()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Сохранить') on item 'LoginMozillaFirefox.Grouping.Сохранить'.", repo.LoginMozillaFirefox.Grouping.СохранитьInfo);
            Validate.Attribute(repo.LoginMozillaFirefox.Grouping.СохранитьInfo, "Text", "Сохранить");
        }

        public void Mouse_Click_Fls7()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IndexMozillaFirefox.Index.Fls7' at 4;8.", repo.IndexMozillaFirefox.Index.Fls7Info);
            repo.IndexMozillaFirefox.Index.Fls7.Click("4;8");
        }

        public void Validate_Выход2()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Выход') on item 'IndexMozillaFirefox.Выход'.", repo.IndexMozillaFirefox.ВыходInfo);
            Validate.Attribute(repo.IndexMozillaFirefox.ВыходInfo, "AccessibleName", "Выход");
        }

        public void Validate_Выход()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='javascript:document.getElementById('logoutForm').submit()') on item 'IndexMozillaFirefox.Выход'.", repo.IndexMozillaFirefox.ВыходInfo);
            Validate.Attribute(repo.IndexMozillaFirefox.ВыходInfo, "Text", "javascript:document.getElementById('logoutForm').submit()");
        }

        public void Mouse_Click_Separator2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Separator' at 79;11.", repo.LoginMozillaFirefox.SeparatorInfo);
            repo.LoginMozillaFirefox.Separator.Click("79;11");
        }

        public void Validate_Find()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Find') on item 'IndexMozillaFirefox.Find'.", repo.IndexMozillaFirefox.FindInfo);
            Validate.Attribute(repo.IndexMozillaFirefox.FindInfo, "Text", "Find");
        }

        public void Mouse_Click_Login()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Login' at 20;16.", repo.LoginMozillaFirefox.Login.LoginInfo);
            repo.LoginMozillaFirefox.Login.Login.Click("20;16");
        }

        public void Key_Sequence_Password2()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'LoginMozillaFirefox.Login.Password'.", repo.LoginMozillaFirefox.Login.PasswordInfo);
            repo.LoginMozillaFirefox.Login.Password.PressKeys("fls7");
        }

        public void Key_Sequence_Password()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'LoginMozillaFirefox.Login.Password'.", repo.LoginMozillaFirefox.Login.PasswordInfo);
            repo.LoginMozillaFirefox.Login.Password.PressKeys("fls7");
        }
        
        public void Key_Sequence_PasswordField()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'LoginMozillaFirefox.Login.Password'.", repo.LoginMozillaFirefox.Login.PasswordInfo);
            repo.LoginMozillaFirefox.Login.Password.PressKeys("{Tab}");
        }

        public void Mouse_Click_Password()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.Password' at 228;22.", repo.LoginMozillaFirefox.Login.PasswordInfo);
            repo.LoginMozillaFirefox.Login.Password.Click("228;22");
        }

        public void Key_Sequence_LoginName()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'fls7' with focus on 'LoginMozillaFirefox.Login.LoginName'.", repo.LoginMozillaFirefox.Login.LoginNameInfo);
            repo.LoginMozillaFirefox.Login.LoginName.PressKeys("fls7");
        }

        public void Mouse_Click_LoginName()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Login.LoginName' at 225;15.", repo.LoginMozillaFirefox.Login.LoginNameInfo);
            repo.LoginMozillaFirefox.Login.LoginName.Click("225;15");
        }

        public void Validate_Login()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Login') on item 'LoginMozillaFirefox.Login.Login'.", repo.LoginMozillaFirefox.Login.LoginInfo);
            Validate.Attribute(repo.LoginMozillaFirefox.Login.LoginInfo, "Text", "Login");
        }

        public void Mouse_Click_Separator()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginMozillaFirefox.Separator' at 111;12.", repo.LoginMozillaFirefox.SeparatorInfo);
            repo.LoginMozillaFirefox.Separator.Click("111;12");
        }

        public void Validate_Войти()
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Войти') on item 'LoginMozillaFirefox.Login.Войти'.", repo.LoginMozillaFirefox.Login.ВойтиInfo);
            Validate.Attribute(repo.LoginMozillaFirefox.Login.ВойтиInfo, "Text", "Войти");
        }

        //public void TC_SelectLanguagesOnAllPages_Open_Browser()
        //{
        //    BrowserHelper.Open_Browser();
        //}
        
        public void Close_App()
        {
            //BrowserHelper.Close_Application_LoginMozillaFirefox();
            BrowserHelper.Kill_Browser();
        }

    }
}