///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexTestMvcSuite.TestCases
{
    /// <summary>
    ///The TC_SelectLanguagesOnAllPages recording.
    /// </summary>
    [TestModule("177acd68-8af7-4ca1-8bff-e82655d8e73e", ModuleType.Recording, 1)]
    public partial class TC_SelectLanguagesOnAllPages : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexTestMvcSuite.RanorexTestMvcSuiteRepository repository.
        /// </summary>
        public static RanorexTestMvcSuite.RanorexTestMvcSuiteRepository repo = RanorexTestMvcSuite.RanorexTestMvcSuiteRepository.Instance;

        static TC_SelectLanguagesOnAllPages instance = new TC_SelectLanguagesOnAllPages();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TC_SelectLanguagesOnAllPages()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TC_SelectLanguagesOnAllPages Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Enter.
        /// </summary>
        [TestVariable("a9bd6d78-8cdf-49d7-a11f-8bb031c9a39b")]
        public string Enter
        {
            get { return repo.Enter; }
            set { repo.Enter = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.1.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Validate_Войти();
            Delay.Milliseconds(0);
            
            Mouse_Click_Separator();
            Delay.Milliseconds(0);
            
            Validate_Login();
            Delay.Milliseconds(0);
            
            Mouse_Click_LoginName();
            Delay.Milliseconds(0);
            
            Key_Sequence_LoginName();
            Delay.Milliseconds(0);
            
            Key_Sequence_PasswordField();
            Delay.Milliseconds(0);
            
            Key_Sequence_Password();
            Delay.Milliseconds(0);
            
            Key_Sequence_Password2();
            Delay.Milliseconds(0);
            
            Mouse_Click_Login();
            Delay.Milliseconds(0);
            
            Validate_Find();
            Delay.Milliseconds(0);
            
            Mouse_Click_Separator2();
            Delay.Milliseconds(0);
            
            Validate_Выход();
            Delay.Milliseconds(0);
            
            Validate_Выход2();
            Delay.Milliseconds(0);
            
            Mouse_Click_Fls7();
            Delay.Milliseconds(0);
            
            Validate_Сохранить();
            Delay.Milliseconds(0);
            
            Mouse_Click_Separator3();
            Delay.Milliseconds(0);
            
            Validate_Save();
            Delay.Milliseconds(0);
            
            Mouse_Click_Separator4();
            Delay.Milliseconds(0);
            
            Mouse_Click_Выход();
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
}
